### ISSUE TITLE
How to uninstall cloudify?

### ISSUE THREAD

**Issue by gammaliu** [cloudify-cosmo/get-cloudify.py#5]
Is there a param in this script get-cloudify.py to uninstall cloudify?

**Comment by nir0s** [comment]
Unfortunately, there's currently no uninstall flag. We're working on a more robust implementation of the CLI's installation which will include uninstallation.

**Comment by nir0s** [comment]
FYI, the website currently specify a way to install Cloudify using deb, rpm or exe packages. You're invited to take a look there.
